# sample to update ini file
- name: update config in ini file
  ini_file:
    dest: /etc/config.ini
    section: "{{item.section}}"
    option: "{{item.key}}"
    value: "{{item.value}}"
  with_items:
    - {section: "section", key: "key1", value: "value1"}
    - {section: "section", key: "key2", value: "value2"}
